<ol><li>You must be at least 13 years of age apon signing up for Skem9.com. If you are found to be under the age of 13 years old, your account will be removed from the Skem9.com database.</li>
		<li>Skem9.com layouts may be down from time to time for special upgrades and / or maintance. Skem9.com cannot inform any of its users before hand of some of the upgrades as it may ruin the suprise for once the site is back up.</li>
	<li>Skem9.com is not responsible for any users postings in the layouts gallery, or on their profile. Skem9.com cannot and does not control the behavior of the users on this site. The views of one user may differ from the views of Skem9.com and its other users. Skem9.com respects the views of one user, but may not agree with that user. User is expected to conrol how much info about themselves they would put within their profiles on Skem9.com. Skem9.com is not associated with any type of transactions, or other form of trading between one person to another.</li>

<li>Skem9.com prohibits the postings of any form of pornography, hate, drug use, violence, and any thing that could be consider unlawfull.</li>
<li>Skem9.com strongly opposes SPAM which is all over the internet. Skem9.com WILL NOT tolerate any form of SPAM within the site. If Skem9.com finds you to be Spaming anykind of content that would and could be considered as SPAM you're account will be deleted, and you IP adderess will be blocked IMMEDIATELY.</li>
<li>Skem9.com also prohits the posting of of SPAM that could be meant for Skem9.c0m users to go to your site, UNLESS the users posting the HTTP adderess to their site has the written consent of a Skem9.com employee.</li>
<li>Any kind of postings on Skem9.com is not private. Once the user (YOU) post something on Skem9.com it becomes Skem9.coms property. Which in turn means that it cannot and willnot be posted on any other site UNLESS it has permission from Skem9.com employees and the user (YOU). In most cases, as long as the user (THE ORIGINAL AUTHOR or CODER) agrees with providing other sites their hard work Skem9.com will agree.</li>
<li>Skem9.com does not agree with stealing layouts or codes. If someone on Skem9.com post a layout that was made by another user on Myspace.com, or on another site the layout will be removed apon verification that it was ideed taken from another source. Same rule applies with other sites taking layouts posted on Skem9.com. If we find that another site has taken a layout from the Skem9.com layouts gallery then charges will be pressed for plagiarism.</li>
<li>Skem9.com is NOT a place for you to host your pictures. We also have banwidth limits, just like any other site out there. If you need a good and quality hosting, I highly suggest using photobucket.com as they will not delete your images once you've reached you maximium banwidth limit. You could also get a paid account and then not even have to worry about banwidth limits anymore. Its cheap to get unlimited banwidth so I would have to say it's you're best bet.</li></ol>